### ISSUE TITLE
Won't allow me to set a payout address

### ISSUE THREAD

**Issue by seanferry** [Bit-Wasp/BitWasp#87]
Under the account tab.

It says vendors have to set up a payout address before they can list any items, no matter how many bitcoin wallet address I try to add it keeps on saying you must enter a a valid address.

Can anyone tell me why or how to resolve it.

Before I could even access the account tab I had to create my own table called bw_payout_address and add the following columns user_id, time, address. Is there something i'm missing here?

**Comment by seanferry** [comment]
Any hints?

**Comment by afk11** [comment]
As you can see, this project is not maintained. I advise you only try use this if you can actually code. It needs some work.

**Comment by seanferry** [comment]
Np i was just trying to get it installed and working on my localhost and then forward it to a pro developer as you can tell I can't code but I wanted to have it working to some degree before I sent it off and possibly wasted my money
