### ISSUE TITLE
New Child Address from HD public address gives error in testnet

### ISSUE THREAD

**Issue by toddmo** [Bit-Wasp/BitWasp#92]
The following code works with the `bitcoin` network but not the `bitcoinTestnet` network. IOW, it works with xpub but not tpub addresses.

```php
				$key = HierarchicalKeyFactory::fromExtended($xpub, NetworkFactory::bitcoinTestnet());
				$path = ($change ? '1' : '0').'/'.$index;
				$child_key = $key->derivePath($path);
				return new Result('data',(new PayToPubKeyHashAddress($child_key->getPublicKey()->getPubKeyHash()))->getAddress());
```

It gives the error: 

> Invalid Bitcoin address: HD key magic bytes do not match network magic bytes

I noticed the constant `xpub` is mentioned in the code, but not the constant `tpub`. It seems like this could be overridden in the testnet network. I don't understand enough about the code for the magic bytes to produce a pull request. Thanks.

**Comment by afk11** [comment]
Posting on the wrong project, think you mean https://github.com/bit-wasp/bitcoin-php

**Comment by toddmo** [comment]
ok I will. Close or delete. Sorry!

**Comment by afk11** [comment]
hmm, one thing looks off, but probably not the cause.. when you call `getAddress() to encode it as a string, you'd need to pass the network there to get the address formatted correctly for testnet. 

re the error: Are you passing a key beginning with `xpub` while you are using testnet? You'd need to use a tpub key in that case, which to me is the most likely cause for the error.
